#!/usr/bin/env Rscript
# -*- mode: R -*-

# plot_aggregate_matrix: produces a plot of ATAC-seq signal around
# features, as generated by calling make_cut_matrix with the
# --aggregate-output option.


suppressMessages(library("RColorBrewer"))
suppressMessages(library("ggplot2"))
suppressMessages(library("grid"))
suppressMessages(library("gtools"))

argv <- commandArgs(TRUE)

bound_file = argv[1]
unbound_file = argv[2]
title = argv[3]
output_filename <- argv[4]

bound = read.delim(file=bound_file, header=TRUE, sep="\t")
if (nrow(bound) > 0) {
   bound$Bound = "Bound"
   bound$FragmentSizeBin <- as.character(bound$FragmentSizeBin)
}

if (unbound_file != "") {
   cat("Unbound file given\n")
   unbound = read.delim(file=unbound_file, header=TRUE, sep="\t")
} else {
   cat("No unbound file given\n")
   unbound = bound[FALSE,]
}
if (nrow(unbound) > 0) {
   unbound$Bound = "Unbound"
   unbound$FragmentSizeBin <- as.character(unbound$FragmentSizeBin)
}

data <- rbind(bound, unbound)
data$FragmentSizeBin <- factor(data$FragmentSizeBin)
data$FragmentSizeBin <- factor(data$FragmentSizeBin, levels=mixedsort(levels(data$FragmentSizeBin)))
if (length(data$Strand) > 0) {
   data$Strand <- as.factor(data$Strand)
}

p <- ggplot(data, aes(x=Position, y=CutPointCountFraction, colour=Strand))
p <- p + geom_line(alpha=0.75) + facet_grid(FragmentSizeBin ~ Bound, scales="free") + ggtitle(title)
p <- p + xlab('Position relative to feature') + ylab('ATAC-seq signal at position / feature count')
p <- p + theme_bw(base_size=10)
p <- p + theme(
  strip.background = element_rect(fill="gray90", colour=FALSE),
  panel.border = element_rect(colour="gray90"),
  panel.margin = unit(1, "lines"),
  plot.title=element_text(vjust=1),
  axis.title.x=element_text(vjust=-0.5),
  axis.title.y=element_text(vjust=1)
)
p <- p + scale_fill_brewer(palette="Dark2")

ggsave(p, file=output_filename, width=11, height=8.5, units="in")

cat(paste("Plot written to", output_filename, "\n"))
