#!/usr/bin/env Rscript
# -*- mode: R -*-

# plot_aggregate_matrix: produces a plot of average ATAC-seq signal
# around motifs, as generated by calling make_cut_matrix
# with the --aggregate-output option.


suppressMessages(library("RColorBrewer"))
suppressMessages(library("ggplot2"))
suppressMessages(library("grid"))
suppressMessages(library("gtools"))

argv <- commandArgs(TRUE)

bound_file = argv[1]
unbound_file = argv[2]
title = argv[3]
pdf_name <- argv[4]

bound = read.delim(file=bound_file, header=TRUE, sep="\t")
bound$Bound = "Bound"

unbound = read.delim(file=unbound_file, header=TRUE, sep="\t")
unbound$Bound = "Unbound"

df <- rbind(bound, unbound)
df$Bin <- factor(df$Bin, levels=mixedsort(levels(df$Bin)))
df$Strand <- as.factor(df$Strand)

p <- ggplot(df, aes(x=Position, y=AverageCutPointCount, colour=Strand))
p <- p + geom_line(alpha=0.75) + facet_grid(Bin ~ Bound, scales="free") + ggtitle(title)
p <- p + xlab('Relative Position') + ylab('ATAC-seq average signal per region')
p <- p + theme_bw(base_size=10)
p <- p + theme(
  strip.background = element_rect(fill="gray90", colour=FALSE),
  panel.border = element_rect(colour="gray90"),
  panel.margin = unit(1, "lines"),
  plot.title=element_text(vjust=1),
  axis.title.x=element_text(vjust=-0.5),
  axis.title.y=element_text(vjust=1)
)
p <- p + scale_fill_brewer(palette="Dark2")

ggsave(p, file=pdf_name, width=11, height=8.5, units="in")

cat(paste("Plot written to", pdf_name, "\n"))
